### ISSUE TITLE
VS2019 C# build and every time create folders....

### ISSUE THREAD

**Issue by avap90** [JohannBlais/InformationBox#17]
**Is your feature request related to a problem? Please describe.**
VS2019 C# build and every time create folders in release folder.
fa,de,ar,fr,...

**Describe the solution you'd like**
no create folder. 

**Describe alternatives you've considered**
no create folder. 

**Additional context**
![image](https://user-images.githubusercontent.com/16488571/181164033-669d1758-08d3-48fc-a3c8-4e8dce0d1345.png)

thank you.

**Comment by JohannBlais** [comment]
Hi, I am not sure if I can actually prevent this. As far as I know this is related to the localisation.
If you have a suggestion, please share :)

**Comment by valimaties** [comment]
https://github.com/FluentValidation/FluentValidation/issues/254
This is from another project, and is discussed on internet for some other projects, too 😊
Maybe this helps...

**Comment by JohannBlais** [comment]
Hi @valimaties,

I had a look at the possible alternatives, but most would imply a breaking change in the package. As it is quite easy to add a post build script to get rid of these folders, I am not planning on altering this behavior.
Thank you for taking the time to submit this improvement request.

**Comment by avap90** [comment]
> 안녕@valimaties,
> 
> 가능한 대안을 살펴보았지만 대부분은 패키지의 주요 변경 사항을 의미합니다. 이러한 폴더를 제거하기 위해 빌드 후 스크립트를 추가하는 것은 매우 쉽기 때문에 이 동작을 변경할 계획이 없습니다. 시간을 내어 이 개선 요청을 제출해 주셔서 감사합니다.

Thank you. I Fixed It!~
