### ISSUE TITLE
Replace the text of the CheckBox

### ISSUE THREAD

**Issue by Aniobodo** [JohannBlais/InformationBox#18]
Could it be possible to replace the text of the (DoNotShowAgain) CheckBox? That will make the CheckBox flexible to be used for other purposes.

**Comment by valimaties** [comment]
Which are the purposes? Could you give an example?

**Comment by Aniobodo** [comment]
To ask another question. Yes simply another question as string. 
Questions like: "Do you want to excecute a function when the MessageBox closes?"

**Comment by JohannBlais** [comment]
Hi, I will have a look at this request. Thank you for your idea !
