### ISSUE TITLE
Assembly version is not set correctly in the .NET 6.0 and .NET Core 3.1 versions

### ISSUE THREAD

**Issue by JohannBlais** [JohannBlais/InformationBox#22]
**Describe the bug**
Reported by @MagicAndre1981: The assembly and file version are incorrect in the latest package.

**To Reproduce**
Open the file properties of the latest NuGet package.
The file version is 1.0.0.0 and the product version is 1.0.0+guid
 

**Expected behavior**
The file version and product version should be set to 1.3.x.x

**Screenshots**
![image](https://user-images.githubusercontent.com/1086147/187607886-0c0a0f0e-18a7-4c8e-b366-78d97d118b7a.png)

**Comment by MagicAndre1981** [comment]
you [excluded the AssemblyInfo.cs](https://github.com/JohannBlais/InformationBox/blob/6f1f970ffba29d6a162de4cf7677988a8266893f/InfoBoxCore/InfoBoxCore.csproj#L14), so this happens. 

If you get duplicate errors, add this to csproj:

    <GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>

**Comment by JohannBlais** [comment]
Thank you for the hint, I need to review the AssemblyInfo stuff. Depending on how it is generated or not, it causes other issues.

**Comment by valimaties** [comment]
[This ](https://stackoverflow.com/questions/34168005/how-to-compile-c-sharp-csproj-into-exe-in-visual-studio-2015-error-cs0579) solution helped. Almost, error of duplication does not raise anymore.
Also, you need to manually set the `AssemblyVersion` number and `FileVersion` number for .Net 6 version and .Net Core, also.

![Versioning](https://user-images.githubusercontent.com/49796453/187924842-c70def99-e54a-4c3f-9543-c6706a79274b.png)

**Comment by JohannBlais** [comment]
Fixed in latest version
