### ISSUE TITLE
Incorrect display with non default Display Scale

### ISSUE THREAD

**Issue by nielswaleson** [JohannBlais/InformationBox#28]
Windows 11
WPF application with one WinForms Form
Windows Display Scale set to 175%

Bug
Buttons to small
Text behind Icon

![Screenshot 2023-07-02 142536](https://github.com/JohannBlais/InformationBox/assets/73241110/d14ec11e-804c-4093-92d8-0180a33cfcc6)

**Comment by JohannBlais** [comment]
Thank you for reporting this issue. I'll have a look and if I can do something about it

**Comment by JohannBlais** [comment]
I changed my display settings to 175% and it still displays correctly.
Could you please share all the parameters you use to display the infobox ?

**Comment by nielswaleson** [comment]
With a standalone winforms app, it looks perfect with the same parameters on the same computer and environment.
In the other application (winforms dll add-in for wpf application) the MS MessageBox looks also perfect.
![Screenshot 2023-07-02 161444](https://github.com/JohannBlais/InformationBox/assets/73241110/6d583a8b-233c-491c-a16b-94c0b6fec976)

**Comment by nielswaleson** [comment]
Scale at 100%, all is OK.
