### ISSUE TITLE
Custom buttons not shown by calling the Show() overload with CheckState out parameter

### ISSUE THREAD

**Issue by Aniobodo** [JohannBlais/InformationBox#34]
The call below does not show the customButtons: new string[] { buttonTexts.Button1, buttonTexts.Button2, buttonTexts.Button3 }

return InformationBox.Show("How are you?", out checkBoxState, title: caption, icon: InformationBoxIcon.Question,
                defaultButton:defaultButton, customButtons: new string[] { buttonTexts.Button1, buttonTexts.Button2, buttonTexts.Button3 },
                showDoNotShowAgainCheckBox: InformationBoxCheckBox.Show, doNotShowAgainText: checkBoxText);

**Comment by JohannBlais** [comment]
Could wou please share more about the version of the package you are using and which .NET framework ?

**Comment by JohannBlais** [comment]
Please add `buttons: InformationBoxButtons.User1User2User3` to your call to instruct the InfoBox to create three custom buttons for you. Otherwise, it defaults to `InformationBoxButtons.OK` which only displays a single OK button.
