### ISSUE TITLE
Show in MDI Form does not center in form

### ISSUE THREAD

**Issue by valimaties** [JohannBlais/InformationBox#37]
**Describe the bug**

When the `InformationBox` is shown in a mdi form the message box is not displaying center to the form. Seems it displaying center in the screen

**To Reproduce**
1. Create a form in a project and set its `IsMdiContainer` to `true`.
2. Write and display a `InformationBox.Show("My message test", this)` message.
3. You will see that `InformationBox` window is centered to screen, not to its parent.

**Expected behavior**
Centering to parent even if parent is mdi container.

**Screenshots**

![Screenshot 2024-05-01 224628](https://github.com/JohannBlais/InformationBox/assets/49796453/e70f5ebf-4402-4ad8-8d87-4321ab3b04b8)

**Desktop (please complete the following information):**
 - OS: W11 x64
 - Framework: .Net Framework 4.8

**Additional context**

In other conditions, like modal or non-modal forms, but not-mdi, the window will center correctly. Only in mdi form is displaying centered to screen, not to its parent.

**Comment by valimaties** [comment]
I've done a debug to see how parameters are implemented and I've saw this:

![image](https://github.com/JohannBlais/InformationBox/assets/49796453/ba8c706e-7b5d-439f-a006-f212fb8c41b4)

for every launch Parent is null
```cs
this.Parent = (Form)Parent; //<- this is null, even if the parameter is a Form
```

![image](https://github.com/JohannBlais/InformationBox/assets/49796453/56902916-8413-4d7d-9b86-6e82a79a770c)

I don't know, maybe this could be repaired somehow. 
I tried to change the `(Form)Parent` with `(Form)parameter` but I get error about some top-level form. 
However, I don't understand the logic of this line. Parent could be something else?

**Comment by JohannBlais** [comment]
Thank you for submitting this issue.
I will have a look

**Comment by JohannBlais** [comment]
Using this sample code, I could not reproduce the problem.

`namespace MdiForm
{
    partial class MainForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.menuStrip1 = new System.Windows.Forms.MenuStrip();
            this.informationBoxToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.openToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.menuStrip1.SuspendLayout();
            this.SuspendLayout();
            // 
            // menuStrip1
            // 
            this.menuStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.informationBoxToolStripMenuItem});
            this.menuStrip1.Location = new System.Drawing.Point(0, 0);
            this.menuStrip1.Name = "menuStrip1";
            this.menuStrip1.Size = new System.Drawing.Size(800, 24);
            this.menuStrip1.TabIndex = 1;
            this.menuStrip1.Text = "menuStrip1";
            // 
            // informationBoxToolStripMenuItem
            // 
            this.informationBoxToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.openToolStripMenuItem});
            this.informationBoxToolStripMenuItem.Name = "informationBoxToolStripMenuItem";
            this.informationBoxToolStripMenuItem.Size = new System.Drawing.Size(102, 20);
            this.informationBoxToolStripMenuItem.Text = "InformationBox";
            // 
            // openToolStripMenuItem
            // 
            this.openToolStripMenuItem.Name = "openToolStripMenuItem";
            this.openToolStripMenuItem.Size = new System.Drawing.Size(180, 22);
            this.openToolStripMenuItem.Text = "Open";
            this.openToolStripMenuItem.Click += new System.EventHandler(this.openToolStripMenuItem_Click);
            // 
            // MainForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(800, 450);
            this.Controls.Add(this.menuStrip1);
            this.IsMdiContainer = true;
            this.MainMenuStrip = this.menuStrip1;
            this.Name = "MainForm";
            this.Text = "Main form 4.8";
            this.menuStrip1.ResumeLayout(false);
            this.menuStrip1.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.MenuStrip menuStrip1;
        private System.Windows.Forms.ToolStripMenuItem informationBoxToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem openToolStripMenuItem;
    }
}

using InfoBox;
using System;
using System.Windows.Forms;

namespace MdiForm
{
    public partial class MainForm : Form
    {
        public MainForm()
        {
            InitializeComponent();
        }

        private void openToolStripMenuItem_Click(object sender, EventArgs e)
        {
            InformationBox.Show("My message test", this);
        }
    }
}
`

**Comment by valimaties** [comment]
I don't know why, mine does not start in center... No matter, I will live it like that, maybe some environmental things happens, aliens, 😂
