### ISSUE TITLE
.NetCore 3.1 support

### ISSUE THREAD

**Issue by MagicAndre1981** [JohannBlais/InformationBox#6]
Can you please add .net core 3.1 support, I get this warning:

`warning NU1701: Package 'InformationBox 1.0.0.29' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.`

**Comment by MagicAndre1981** [comment]
I tried to implement it with #7

**Comment by JohannBlais** [comment]
Please have a look at the latest version and let me know if it works for you

**Comment by MagicAndre1981** [comment]
> Please have a look at the latest version and let me know if it works for you

it works, but you haven't [added sourcelink support](https://github.com/JohannBlais/InformationBox/issues/1) to` InfoBoxCore.csproj`.

**Comment by MagicAndre1981** [comment]
[this commit is not enough](https://github.com/JohannBlais/InformationBox/commit/7c61c3ae519060bdb3825e9cbe86efa4d39bd246). you need to [add the changes like I did in my PR](https://github.com/JohannBlais/InformationBox/pull/2/files).

**Comment by JohannBlais** [comment]
The commit you are mentioning was not meant to address the sourcelink part. It was to support the GitHub Packages release. I will add sourcelink support in the upcoming days.

**Comment by MagicAndre1981** [comment]
ok, thanks

**Comment by JohannBlais** [comment]
I have pushed a new version with support for source link. The symbols package is on Nuget as well. Check it out !

**Comment by MagicAndre1981** [comment]
thanks, this version works fine, PDB was loaded from nuget symbol server and stepping into code works for .net core 3.1
