### ISSUE TITLE
.Net 5 support

### ISSUE THREAD

**Issue by MagicAndre1981** [JohannBlais/InformationBox#8]
.Net 5 is the next major .net version which replace .net 4.x and is based on .net core code base. 

Microsoft [released the last RC](https://devblogs.microsoft.com/dotnet/announcing-net-5-0-rc-2/) and it would be to also have .net 5 support when .net 5 is released as stable version.

Here is a [breaking change to 3.1 in terms of used SDK](https://docs.microsoft.com/en-us/dotnet/core/compatibility/winforms#winforms-and-wpf-apps-use-microsoftnetsdk)

**Comment by MagicAndre1981** [comment]
For your info, .NET 5.0 [will be out next week](https://devblogs.microsoft.com/dotnet/net-5-0-launches-at-net-conf-november-10-12/)

**Comment by MagicAndre1981** [comment]
ok, I tried to add it in #16 , I created a demo app and used the generated nuget and runs fine so far:

![image](https://user-images.githubusercontent.com/8274816/102073011-f2d78780-3e02-11eb-803c-6be04529bf8b.png)

**Comment by JohannBlais** [comment]
I am considering dropping support for previous versions of dotnet in favour of .net 6.
I would keep the previous packages but the new ones would only target .net 6.
Would that work for you?

**Comment by MagicAndre1981** [comment]
no, please **not**. I still prefer classic **.net 48, net core 3.1 and .net 6** support as nuget package manager would show me incompatible package updates because PM UI doesn't support the allowVersions entry for PackageReferenceInclude entries.

**Comment by JohannBlais** [comment]
Alright, I'll replace the .NET 4 client profile with 4.8, keep 3.1 until it is no longer support (Dec. 2022), and add support for .net 6 in parallel

**Comment by JohannBlais** [comment]
Hi @MagicAndre1981, I have published a new version compatible with the framework mentione d above. Please feel free to have a look :)

**Comment by MagicAndre1981** [comment]
> Please feel free to have a look :)

works in .net 6 WinForms application. Only the file version for .net core 3.1 (0.0.0) and net 6.0 (1.0.0) dlls are not correctly set

**Comment by JohannBlais** [comment]
I have now fixed the issue. Thank you for your help !

**Comment by MagicAndre1981** [comment]
> Hi @MagicAndre1981, I have published a new version compatible with the framework mentione d above. 

this week .net7 will be released so having this also added would be nice
